config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.login.views import *
from django.conf import settings
from django.conf.urls.static import static

# Aqui se pone la configuracion de las url del proyecto, el include es para llamar las urls de las apps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.inventario.urls')),
    path('', include('core.login.urls')),
    path("user/",include("core.user.urls"))
]

# agrego la configuracion del los archivos media si esta en desarrollo
# if "WEBSITE_HOSTNAME" not in os.environ:
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/inventario/urls.py
from django.urls import path
from core.inventario.views.categoria.views import *
from core.inventario.views.cliente.views import *
from core.inventario.views.compra.views import CompraCreateView, CompraDeleteView, CompraListView, CompraUpdateView
from core.inventario.views.proveedor.views import ProveedorCreateView, ProveedorDeleteView, ProveedorListView, ProveedorUpdateView
from core.inventario.views.venta.views import *
from core.inventario.views.dashboard.views import *
from core.inventario.views.producto.views import *

app_name = 'inventario'

urlpatterns = [
    #Categoria
    path('categoria/list/', CategoriaListView.as_view(), name='categoria_list'),
    path('categoria/add/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categoria/update/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categoria/delete/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    # producto
    path('producto/list/', ProductoListView.as_view(), name='producto_list'),
    path('producto/add/', ProductoCreateView.as_view(), name='producto_create'),
    path('producto/update/<int:pk>/', ProductoUpdateView.as_view(), name='producto_update'),
    path('producto/delete/<int:pk>/', ProductoDeleteView.as_view(), name='producto_delete'),

    # cliente
    path('cliente/list/', ClienteListView.as_view(), name='cliente_list'),
    path('cliente/add/', ClienteCreateView.as_view(), name='cliente_create'),
    path('cliente/update/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('cliente/delete/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_delete'),

    # proveedor
    path('proveedor/list/', ProveedorListView.as_view(), name='proveedor_list'),
    path('proveedor/add/', ProveedorCreateView.as_view(), name='proveedor_create'),
    path('proveedor/update/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_update'),
    path('proveedor/delete/<int:pk>/', ProveedorDeleteView.as_view(), name='proveedor_delete'),

    # compra
    path('compra/list/', CompraListView.as_view(), name='compra_list'),
    path('compra/add/', CompraCreateView.as_view(), name='compra_create'),
    path('compra/update/<int:pk>/', CompraUpdateView.as_view(), name='compra_update'),
    path('compra/delete/<int:pk>/', CompraDeleteView.as_view(), name='compra_delete'),

    #Home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    #Venta
    path('venta/list/', VentaListView.as_view(), name='venta_list'),
    path('venta/add/', VentaCreateView.as_view(), name='venta_create'),
    path('venta/delete/<int:pk>/', VentaDeleteView.as_view(), name='venta_delete'),
    path('venta/update/<int:pk>/', VentaUpdateView.as_view(), name='venta_update'),

    
]        

core/user/urls.py
from django.urls import path
from core.user.views import *


app_name = 'user'

urlpatterns = [
    #Usuario
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('cambio_contra/', UserCambioContrasena.as_view(), name='cambio_contra'),
    ]

core/inventario/views/dashboard/views.py
from django.db.models.functions import Cast
from datetime import datetime
import calendar

from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.db.models import FloatField
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from core.inventario.models import Venta, Producto, DetalleVenta

from random import randint

meses_espanol = {
        1: 'enero',
        2: 'febrero',
        3: 'marzo',
        4: 'abril',
        5: 'mayo',
        6: 'junio',
        7: 'julio',
        8: 'agosto',
        9: 'septiembre',
        10: 'octubre',
        11: 'noviembre',
        12: 'diciembre',
    }

class DashboardView(TemplateView):
    template_name= 'dashboard.html'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_grafico_venta_mes':
                data = {
                    'name': 'Precio de venta',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': self.get_grafico_venta_mes()
                }
            elif action == 'get_grafico_producto_venta_mes':
                valoresG=self.get_grafico_producto_venta_mes()
                data = {"chart":{
                    'name': 'Porcentaje',
                    'colorByPoint': True,
                    'data': valoresG[0],
                },
                "mes":meses_espanol[valoresG[1]],
                "anio":valoresG[2]

                    
                }
            elif action == 'get_grafico_online':
                data = {'y': randint(1, 100)}
                print(data)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data={}
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_grafico_venta_mes(self):
        data=[]
        try:
            year=datetime.now().year
            for m in range(1,13):
                Total=Venta.objects.filter(Date_joined__year=year, Date_joined__month=m).aggregate(Total=Cast(Coalesce(Sum('Total'), 0.00),FloatField()))
                data.append(Total['Total'])
        except Exception as e:
            print(str(e))
        return data
    
    def get_grafico_producto_venta_mes(self):
        data = []
        year = datetime.now().year
        mes = datetime.now().month
        try:
            for p in Producto.objects.all():
                total = DetalleVenta.objects.filter(Venta__Date_joined__year=year, Venta__Date_joined__month=mes, Produ_id=p.id).aggregate(r=Cast(Coalesce(Sum('Subtotal'), 0.00),FloatField())).get("r",0)
                if total > 0:
                    data.append({
                        'name': p.Nombre,
                        'y': float(total)
                    })
        except Exception as e:
            print(e)
        return [data, mes, year]


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['panel']='Panel de administrador'
        context['grafico_venta_mes']=self.get_grafico_venta_mes()
        context['ventas']=Venta.objects.all().order_by("-Date_joined")[0:10]
        produ=Producto.objects.filter(Stock__lt=6)
        context['alert_produ']={"vali":True if produ.exists() else False,"produ": produ }
        return context

templates/body.html
{% extends 'home.html' %} 
{% block body %}
<body class="hold-transition layout-top-nav">
  {% csrf_token %}
  <div class="wrapper">
    <!-- Header -->
    {% include 'header.html' %}
    <!-- Content -->
    <div class="content-wrapper">
      <div class="content-header">
        <div class="container">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">
                Bienvenido <small>{{ request.user.get_full_name }}</small>
              </h1>
            </div>
            {% if request.path != '/dashboard/' %}
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                  <a href="{% url 'inventario:dashboard' %}">Inicio</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ list_url }}">{{ entity }}</a>
                </li>
              </ol>
            </div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="content">
        <div class="container">{% block content %} {% endblock %}</div>
      </div>
      
    </div>
    <!-- Footer -->
    {% include 'footer.html' %}
  </div>
{% comment %} Modal {% endcomment %}
<div
  class="modal fade"
  id="modal-contra"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <b class="b-modal-title"
            ><i class="far fa-edit"></i> Cambio de contraseña</b
          >
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex flex-column justify-content-center my-2">
        <form id="cambio_contra_form">
        <div class="form-group">
          <label for="contra_actual">Contraseña actual</label>
          <input type="password" required class="form-control" id="contra_actual" name="password">
        </div>
        <div class="form-group">
          <label for="nueva_contra_1">Nueva contraseña</label>
          <input type="password" required class="form-control" id="nueva_contra_1" name="password1">
        </div>
        <div class="form-group">
          <label for="nueva_contra_2">Confirmar contraseña</label>
          <input type="password" required class="form-control" id="nueva_contra_2" name="password2">
        </div>
        <button type="submit" class="btn btn-primary btn-bg-morado-2">Cambiar</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% comment %} EndModal {% endcomment %}
  <script>
    {% if messages %}
    var html = '<p>';
        {% for message in messages %}
        html += '{{ message }}<br>';
        {% endfor %}
        html += '</p>';
        Swal.fire({
            title: 'Error!',
            html: html,
            icon: 'error'
            });
        {% endif %}
  {% comment %} Modal de cambio de contraseña {% endcomment %}
  const modal = $("#modal-contra")
  const btn_cambio=$("#cambio_contra")
  const form_cambio_contra = $("#cambio_contra_form")
  
  btn_cambio.on("click",function(e){
    e.preventDefault();
    modal.modal("show");
  })

  form_cambio_contra.on("submit",function(e){
    e.preventDefault()
    form_data=new FormData(this)
    submit_with_ajax(
      "{% url 'user:cambio_contra' %}",
      "Cambio contraseña", 
      "¿Confirma cambio de contraseña?", 
      form_data,
    (data)=>{
      Swal.fire({
            title: 'Contraseña',
            text: "Cambio de contraseña correcto",
            icon: 'success'
          }).then(function(){
            window.location.href="{% url 'login' %}"
          });
      
    })
  })
  </script>
  {% block javascript %} {% endblock %}
</body>
{% endblock %}

templates/dashboard.html
{% extends 'body.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static "dashboard/css/carrusel.css" %}">
<script src="{% static "dashboard/js/carrusel.js" %}"></script>
<script src="{% static 'libs/highcharts-8.1.2/highcharts.js' %}"></script>
<script src="{% static 'libs/highcharts-8.1.2/modules/exporting.js' %}"></script>
<script src="{% static 'libs/highcharts-8.1.2/modules/export-data.js' %}"></script>
<script src="{% static 'libs/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %} 
{% block content %}
<div class="container-fluid">
  <div class="w-100 d-flex flex-column align-items-center">
    <img src="{% static "img/logo-favi.png" %}" alt="" class="img-fluid col-12
    col-sm-6 logo-dash mb-3">
    <div class="d-flex flex-column flex-md-row mb-3">
      <div style="margin-right:20px;" class="w-100">
        {% comment %} Carrousel 1 {% endcomment %}
        <div
        class="align-self-center container-carousel col-12"
       >
        {% comment %} Contenedor de imagenes {% endcomment %}
        <div class="carruseles-1 carruseles" id="slider-1">
          <section class="slider-section-1 slider-section">
            <img src="{% static "img/slider-1-1.png" %}" alt="" />
          </section>
          <section class="slider-section-1 slider-section">
            <img src="{% static "img/slider-1-2.png" %}" alt="" />
          </section>
        </div>
        <div class="btn-left-1 btn-left"><i class="fas fa-caret-left"></i></div>
        <div class="btn-right-1 btn-right"><i class="fas fa-caret-right"></i></div>
        </div>
        {% comment %} Fin-carrousel 1 {% endcomment %}
      </div>
      <div style="margin-left:20px;" class="w-100">
        {% comment %} Carrousel 2 {% endcomment %}
        <div
        class="align-self-center container-carousel col-12"
       >
        {% comment %} Contenedor de imagenes {% endcomment %}
        <div class="carruseles-2 carruseles" id="slider-2">
          <section class="slider-section-2 slider-section">
            <img src="{% static "img/slider-2-1.png" %}" alt="" />
          </section>
          <section class="slider-section-2 slider-section">
            <img src="{% static "img/slider-2-2.png" %}" alt="" />
          </section>
        </div>
        <div class="btn-left-2 btn-left"><i class="fas fa-caret-left"></i></div>
        <div class="btn-right-2 btn-right"><i class="fas fa-caret-right"></i></div>
        </div>
        {% comment %} Fin-carrousel 2 {% endcomment %}
      </div>
    </div>
  </div>
  <div class="mb-3">
    {% if alert_produ.vali %}
    <div class="alert alert-info alert-dismissible">
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-hidden="true"
      >
        ×
      </button>
      <h5>
        <i class="icon fas fa-info"></i> ¡<a
          class="link_hover"
          href="{% url 'inventario:producto_list' %}"
          >Productos</a
        >
        con poco stock!
      </h5>
      <ul>
        {% for produ in alert_produ.produ %}
        <li>
          {{produ.Nombre}}:
          <span class="text-warning">{{produ.Stock}} stock</span>
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    <h3 class="text-center">
      <i class="fas fa-shopping-cart"></i> Las últimas ventas realizadas
    </h3>
    <table class="table border table-dash">
      <thead>
        <tr>
          <th scope="col">Nro</th>
          <th scope="col">Cliente</th>
          <th scope="col">Fecha de registro</th>
          <th scope="col">Subtotal</th>
          <th scope="col">Iva</th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
        {% if not ventas %}
        <tr>
          <th colspan="6" class="text-center">Sin ventas</th>
        </tr>
        {% else %} {% for venta in ventas %}
        <tr>
          <th scope="row">{{venta.id}}</th>
          <td>{{venta.Cli.get_nombre}}</td>
          <td>{{venta.Date_joined|date:"Y-m-d"}}</td>
          <td>{{venta.Subtotal}}</td>
          <td>{{venta.Iva}}</td>
          <td>{{venta.Total}}</td>
          {% endfor %}
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
  <div class="d-flex flex-column flex-md-row justify-content-between">
    <div class="row col-12 col-md-6 mb-3">
      <div class="col-lg-12">
        <div id="container"></div>
      </div>
    </div>

    <div class="row col-12 col-md-6">
      <div class="col-lg-12">
        <div id="container-pie"></div>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript">
  var graphcolumn = Highcharts.chart("container", {
    chart: {
      type: "column",
    },
    title: {
      text: "Reporte de ventas del año 2023",
    },
    subtitle: {
      text: "Reporte de columnas",
    },
    xAxis: {
      categories: [
        "Enero",
        "Febrero",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agosto",
        "Septiembre",
        "Octubre",
        "Noviembre",
        "Diciembre",
      ],
      crosshair: true,
    },
    yAxis: {
      min: 0,
      title: {
        text: "Valores $",
      },
    },
    tooltip: {
      headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
      pointFormat:
        '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
        '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
      footerFormat: "</table>",
      shared: true,
      useHTML: true,
    },
    plotOptions: {
      column: {
        pointPadding: 0.2,
        borderWidth: 0,
      },
    },
  });

  let graphpie = Highcharts.chart("container-pie", {
    chart: {
      plotBackgroundColor: null,
      plotBorderWidth: null,
      plotShadow: false,
      type: "pie",
    },
    title: {
      text: "Porcentaje de venta de productos por el mes de Agosto del año 2023",
    },
    tooltip: {
      pointFormat: "{series.name}: <b>{point.percentage:.1f}%</b>",
    },
    accessibility: {
      point: {
        valueSuffix: "%",
      },
    },
    plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: "pointer",
        dataLabels: {
          enabled: true,
          format: "<b>{point.name}</b>: {point.percentage:.1f} %",
        },
      },
    },
  });

  function get_grafico_venta_mes() {
    $.ajax({
      url: window.location.pathname, //window.location.pathname
      type: "POST",
      data: {
        action: "get_grafico_venta_mes",
      },
      dataType: "json",
    })
      .done(function (data) {
        if (!data.hasOwnProperty("error")) {
          graphcolumn.addSeries(data);
          return false;
        }
        message_error(data.error);
      })
      .fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ": " + errorThrown);
      })
      .always(function (data) {});
  }

  function get_grafico_producto_venta_mes() {
    $.ajax({
      url: window.location.pathname, //window.location.pathname
      type: "POST",
      data: {
        action: "get_grafico_producto_venta_mes",
      },
      dataType: "json",
    })
      .done(function (data) {
        if (!data.hasOwnProperty("error")) {
          graphpie.addSeries(data.chart);
          graphpie.setTitle({
            text:
              "Porcentaje de venta de productos por el mes de " +
              data.mes +
              " del año " +
              data.anio,
          });
          return false;
        }
        message_error(data.error);
      })
      .fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ": " + errorThrown);
      })
      .always(function (data) {});
  }

  $(function () {
    get_grafico_venta_mes();

    get_grafico_producto_venta_mes();
  });
</script>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}
<form method="post" action=".">
    <div class="card card-default">
    <div class="card-header bg-morado-2 text-white">
    <h3 class="card-title">
    <i class="fas fa-trash"></i>
    {{ title }}
    </h3>
    </div>
    <div class="card-body">
        {% csrf_token %}
        <input type="hidden" name="action" value="{{ action }}">
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar un registro</h5>
            <ul>
                {% for field in form %}
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
            </div>
        {% endif %}
        <div class="alert alert-danger alert-dismissible">
            <h5><i class="icon fas fa-ban"></i> Notificacion!</h5>
            ¿Estas seguro de eliminar el registro Nro {{ object.id }}?
            </div>
          <div class='card-footer'></div>
          <button type="submit" class="btn btn-primary btn-flat btn-bg-morado-2"><i class="fas fa-save"></i> Si, aceptar</button>

          <a href="{{ list_url }}" class="btn btn-info btn-flat"> <i class="fas fa-times"> Cancelar</i></a>
          </div>
    </div>
</div>
</form>
<script>
    //Obtengo el evento click del boton submit
    $('form').on('submit', function (e) {
            e.preventDefault();
            var parametros = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parametros, function () {
                location.href = '{{ list_url }}';
            });
        });
</script>
{% endblock %}

templates/footer.html
{% load static %}
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      dasixinventario@gmail.com
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2023 <span class="text-primary">Dasix</span>.</strong> Todos los derechos reservados.
  </footer>

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary bg-morado-1">
    <div class="container">
        <a href="{% url 'inventario:dashboard' %}" class="navbar-brand">
            <img src="{% static 'img/logo-favi.png' %}" alt="Dasix logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Dasix</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'inventario:dashboard' %}" class="nav-link"><i class="fas fa-home"></i> Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'inventario:categoria_list' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="{% url 'inventario:producto_list' %}" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="{% url 'inventario:cliente_list' %}" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="{% url 'inventario:proveedor_list' %}" class="dropdown-item"><i class="fas fa-parachute-box"></i> Proveedores</a></li>
                        <li><a href="{% url 'inventario:compra_list' %}" class="dropdown-item"><i class="fas fa-shopping-bag"></i> Compras</a></li>
                        <li><a href="{% url 'inventario:venta_list' %}" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                        <li><a href="{% url 'user:user_list' %}" class="dropdown-item"><i class="fas fa-user"></i> Usuarios</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-users-cog"></i> {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                        Último Acceso: {{request.user.last_login|date:"Y-m-d"}}
                    </span>
                    <div class="dropdown-divider"></div>
                    <a id="cambio_contra" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

templates/list.html
{% extends 'body.html' %}
{% load static %}
{% block head %}
<!--jquery-ui-->
<link  href="{% static 'libs/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
<script src="{% static 'libs/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'libs/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
<link rel="stylesheet" href="{% static 'libs/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
<script src="{% static 'libs/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'libs/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

{% block head_list %}
{% endblock %}

{% endblock %}

{% block content %}
<div class="card card-primary">
    <div class="card-header bg-morado-2">
    <h3 class="card-title">
    <i class="fas fa-search"></i>
    {{ title }}
    </h3>
    </div>
    <div class="card-body">
        <table class="table" id="data">
            <thead>
                {% block columnas %}

                {% endblock %}
            </thead>
            <tbody>
                {% block rows %}

                {% endblock %}
 
            </tbody>
          </table>
          <div class='card-footer'></div>
          <a href= "{{ create_url }}" class="btn btn-primary btn-flat btnTest btn-bg-morado-2"><i class="fas fa-plus"></i> Nuevo registro</a>
          <a href="{{ list_url }}" class="btn btn-success"><i class="fas fa-sync"></i> Actualizar</a>
          </div>
    </div>

</div>
{% endblock %}

{% block javascript %}
<script type='application/javascript'>
$(function(){
    $('#data').DataTable({
        responsive: false,
        autowidth: false
    });
    $('.btnTest').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:categoria_list' %}",
            type: 'POST',
            data: {id: 1},
            dataType: 'json'
        }).done(function (data) {
            console.log(data);
        }).fail(function (jqXHR, textStatus, errorThrown) {
            alert(textStatus+': '+errorThrown);
        }).always(function (data) {

        });
    });

});
</script>

{% endblock %}